apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  #BASE64 String
  #* With the terminal
  #* echo -n postgres | base64
  # postgres
  DB_USER: cG9zdGdyZXM=
  # EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=